// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDdus8WSGfghT7pTWQB9k24R-6qy1Naqc',
    appId: '1:705510204267:web:e9a085e7750ddb92f1a22e',
    messagingSenderId: '705510204267',
    projectId: 'the-notes-36hours-tutor',
    authDomain: 'the-notes-36hours-tutor.firebaseapp.com',
    storageBucket: 'the-notes-36hours-tutor.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQkAtH6BVOxx1YfmywO-jTZtSYzuNAK_I',
    appId: '1:705510204267:android:a97ce13c116752a4f1a22e',
    messagingSenderId: '705510204267',
    projectId: 'the-notes-36hours-tutor',
    storageBucket: 'the-notes-36hours-tutor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8eEGWp-OceGQmain-cb0bj0IoScc-lXc',
    appId: '1:705510204267:ios:6ea26a2a4a176230f1a22e',
    messagingSenderId: '705510204267',
    projectId: 'the-notes-36hours-tutor',
    storageBucket: 'the-notes-36hours-tutor.appspot.com',
    iosClientId: '705510204267-2vlmsik1estr7afhskohtef57pluubmi.apps.googleusercontent.com',
    iosBundleId: 'com.thenotes.thenotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8eEGWp-OceGQmain-cb0bj0IoScc-lXc',
    appId: '1:705510204267:ios:6059a49f60486463f1a22e',
    messagingSenderId: '705510204267',
    projectId: 'the-notes-36hours-tutor',
    storageBucket: 'the-notes-36hours-tutor.appspot.com',
    iosClientId: '705510204267-k53oh29u2onhqalufcc1dpmd7mv1svab.apps.googleusercontent.com',
    iosBundleId: 'com.thenotes.thenotes.RunnerTests',
  );
}
